import { Injectable, computed, signal } from '@angular/core';
import { Hospital,Incident,OperationalAlert,PublicAlert,Resource,ResponsePlan,Shelter,TimelineEvent } from '../models/domain.models';
const now=Date.now(), iso=(mins:number)=>new Date(now-mins*60000).toISOString();
const incidents:Incident[]=[{id:'inc-tornado-01',title:'Lewisville Tornado Response',type:'Tornado',description:'Confirmed tornado damage corridor affecting residences, utilities, and transportation. Synthetic exercise scenario.',severity:'Critical',status:'Escalated',location:'Lewisville, TX',county:'Denton',coordinates:{latitude:33.0462,longitude:-96.9942},reportedAt:iso(138),commander:'Jordan Lee',populationAffected:18450,impactRadiusKm:8,completeness:87,objectives:['Protect life in the impact corridor','Complete primary search by 18:00','Maintain hospital distribution'],risks:['Downed energized lines','Secondary severe-weather cells','Congested access routes']},{id:'inc-flood-02',title:'Clear Creek Flood Monitoring',type:'Flood',description:'Elevated creek gauges following training-scenario rainfall.',severity:'Moderate',status:'Monitoring',location:'Denton, TX',county:'Denton',coordinates:{latitude:33.2148,longitude:-97.1331},reportedAt:iso(390),commander:'Morgan Patel',populationAffected:2700,impactRadiusKm:4.5,completeness:74,objectives:['Monitor low-water crossings','Stage swift-water capability'],risks:['Rapid overnight rise','Road inundation']}];
const hospitalNames=['Medical City Lewisville','Texas Health Presbyterian Denton','Medical City Denton','Baylor Scott & White Centennial','Cook Children’s Prosper','Methodist Southlake'];
const hospitals:Hospital[]=hospitalNames.map((name,i)=>({id:`h-${i+1}`,name,type:i===4?'Pediatric':'Acute care',location:['Lewisville','Denton','Denton','Frisco','Prosper','Southlake'][i]+' (demo)',distanceKm:[3.1,20.4,22.1,24.8,27.2,19.6][i]!,status:i===2?'Limited':'Operational',emergencyStatus:i===1?'High census':'Accepting',traumaLevel:['III','III','IV','III','Pediatric','IV'][i]!,totalBeds:120+i*38,availableBeds:[18,31,12,42,20,15][i]!,icuAvailable:[3,6,2,8,4,2][i]!,diversion:i===2,helipad:i!==5,contact:'EOC coordination channel',lastUpdated:iso(i*4+2),dataSource:'Synthetic demonstration feed',coordinates:{latitude:33.04+i*.035,longitude:-96.99-i*.025}}));
const shelters:Shelter[]=Array.from({length:8},(_,i)=>({id:`s-${i+1}`,name:['Lewisville Civic Center','Vista Ridge Community Hub','Highland Village Center','Flower Mound Activity Center','Lake Dallas Community Hall','Denton North Reception Center','The Colony Recreation Center','Frisco Family Assistance Site'][i]!,address:`${200+i*117} Demo Way, Denton County, TX`,status:i===6?'Standby':'Open',capacity:120+i*45,occupancy:[91,132,44,188,64,108,0,147][i]!,accessibility:true,medicalSupport:i%2===0,pets:i%3!==0,backupPower:i!==3,food:true,water:true,connectivity:i!==4,contact:'Demo shelter desk',lastUpdated:iso(i*3+1),coordinates:{latitude:33.03+i*.018,longitude:-97.02+i*.02}}));
const types=['Ambulance','Fire engine','Rescue unit','Police unit','Public works crew','Utility crew','Mobile command unit','Generator','Bus','Helicopter','Drone','Volunteer team','Medical team','Supply cache'];
const statuses:Resource['status'][]=['Available','Assigned','EnRoute','Deployed','Returning','Unavailable','Maintenance'];
const resources:Resource[]=Array.from({length:20},(_,i)=>({id:`r-${i+1}`,name:`${types[i%types.length]} ${String(i+1).padStart(2,'0')}`,type:types[i%types.length]!,status:statuses[i%statuses.length]!,agency:['Denton County Demo','Lewisville Demo Fire','Regional Mutual Aid'][i%3]!,incidentId:i%4===0?undefined:'inc-tornado-01',coordinates:{latitude:33.01+(i%5)*.025,longitude:-97.08+(i%4)*.035},updatedAt:iso(i+1)}));
const timeline:TimelineEvent[]=Array.from({length:10},(_,i)=>({id:`tl-${i}`,incidentId:'inc-tornado-01',at:iso(125-i*11),type:['Command','Operations','Safety','Resource'][i%4]!,title:['Unified command established','Primary search sector updated','Utility hazard perimeter expanded','Mutual aid checked in'][i%4]!,detail:'Exercise update recorded and shared with command staff.',actor:['Jordan Lee','Operations Section','Safety Officer','Staging Manager'][i%4]!}));
const alerts:OperationalAlert[]=[{id:'wx1',type:'Weather',severity:'Critical',title:'Tornado warning — exercise',detail:'Synthetic polygon intersects the incident area.',status:'Active',updatedAt:iso(4)},{id:'wx2',type:'Weather',severity:'Major',title:'Severe thunderstorm warning — exercise',detail:'Damaging winds possible in scenario.',status:'Active',updatedAt:iso(12)},{id:'wx3',type:'Weather',severity:'Moderate',title:'Flood watch — exercise',detail:'Low-water crossings under observation.',status:'Monitoring',updatedAt:iso(32)},{id:'road1',type:'Traffic',severity:'Major',title:'FM 1171 closure',detail:'Emergency access only near demo impact corridor.',status:'Active',updatedAt:iso(8)}];
const plan:ResponsePlan={id:'plan-01',incidentId:'inc-tornado-01',situationSummary:'A tornado damage corridor has disrupted utilities and access across west Lewisville. Search, medical distribution, and route control are immediate priorities.',objectives:['Complete primary search of highest-probability zones','Preserve emergency access and distribute patients','Provide accessible shelter for displaced residents'],recommendations:[{id:'rec-1',priority:'Immediate',category:'Life safety',action:'Deploy paired search teams to sectors Alpha and Bravo after utility hazard briefing.',reason:'Highest modeled concentration of damaged structures and delayed welfare checks.',evidence:['911 call cluster — synthetic','Damage assessment layer — demo'],expectedOutcome:'Accelerated primary search with controlled responder exposure.',responsibleRole:'Operations Section Chief',startTime:'Now',duration:'90 minutes',confidence:88,dependencies:['Utility hazard map','Accountability check'],safetyConstraints:['Maintain two-team contact','Do not enter energized exclusion zones'],status:'Under Review'},{id:'rec-2',priority:'High',category:'Hospital coordination',action:'Use distributed patient routing and reconfirm capacity every 15 minutes.',reason:'Prevents overload at the closest emergency department.',evidence:['Synthetic bed capacity feed','Travel-time estimate'],expectedOutcome:'Balanced emergency department arrivals.',responsibleRole:'Hospital Coordinator',startTime:'Within 15 minutes',duration:'4 hours',confidence:82,dependencies:['Medical transport channel'],safetyConstraints:['Clinical destination decisions remain with medical control'],status:'AI Draft'},{id:'rec-3',priority:'High',category:'Public communications',action:'Issue an approved multilingual shelter and road-closure update.',reason:'Reduces entry into the damage corridor and directs displaced residents.',evidence:['Closure list','Open shelter capacity'],expectedOutcome:'Safer movement and fewer route conflicts.',responsibleRole:'Public Information Officer',startTime:'Within 30 minutes',duration:'30 minutes',confidence:91,dependencies:['Command approval','Translation review'],safetyConstraints:['Verify all locations before release'],status:'AI Draft'}],dataGaps:['Field-verified structure count','Current utility isolation boundary'],assumptions:['Mutual-aid resources arrive within 45 minutes'],risks:['Secondary storm cell','Communications congestion'],confidence:85,sources:['Synthetic CAD summary','Demo weather layer','Synthetic hospital and shelter feeds'],generatedAt:iso(14),engineVersion:'Sentinel Planning Engine — deterministic demo v1'};
@Injectable({providedIn:'root'}) export class DemoDataService {
 private readonly incidentState=signal(incidents);private readonly resourceState=signal(resources);private readonly planState=signal(plan);private readonly publicAlertState=signal<PublicAlert[]>([]);
 readonly incidents=this.incidentState.asReadonly();readonly activeIncidents=computed(()=>this.incidentState().filter(x=>!['Closed','Cancelled'].includes(x.status)));readonly hospitals=signal(hospitals).asReadonly();readonly shelters=signal(shelters).asReadonly();readonly resources=this.resourceState.asReadonly();readonly timeline=signal(timeline).asReadonly();readonly alerts=signal(alerts).asReadonly();readonly plan=this.planState.asReadonly();readonly publicAlerts=this.publicAlertState.asReadonly();
 getIncident(id:string):Incident|undefined{return this.incidentState().find(x=>x.id===id)}
 createIncident(input:Omit<Incident,'id'|'completeness'|'objectives'|'risks'>):Incident{const item={...input,id:`inc-${crypto.randomUUID()}`,completeness:68,objectives:['Validate initial situation','Establish incident objectives'],risks:['Pending field verification']};this.incidentState.update(items=>[item,...items]);return item}
 updateRecommendation(id:string,status:ResponsePlan['recommendations'][number]['status']):void{this.planState.update(p=>({...p,recommendations:p.recommendations.map(r=>r.id===id?{...r,status}:r)}))}
 assignResource(id:string):void{this.resourceState.update(items=>items.map(r=>r.id===id?{...r,status:'Assigned',incidentId:'inc-tornado-01',updatedAt:new Date().toISOString()}:r))}
 saveAlert(alert:PublicAlert):void{this.publicAlertState.update(items=>[alert,...items])}
}
